#!/usr/bin/env bash
#===============================================================================
# test/docs_gate.sh - Vyb SDK mandatory-documentation ship gate (issue #175).
#
# Policy: no SDK ships without docs. This gate exits 0 ONLY if every required
# document exists, is non-empty, and contains no stale placeholder wording
# (e.g. "placeholder for future").
#
# Required set:
#   - docs/refman/PROGRAMMERS_GUIDE.md
#   - docs/refman/index.md
#   - every generated module page under docs/refman/ (marked by
#     "generated by tools/refman.py")
#   - doc/MANIFEST.md, doc/DEVELOPER_TOOLING.md, doc/DOCS_POLICY.md,
#     doc/GENERIC_ASPECT_CONFORMANCE.md, doc/FEATURE_STATUS.md
#   - CHANGELOG.md
#   - docs/sdk/GETTING_STARTED.md, docs/sdk/INSTALL.md
#
# Prints a per-file PASS/FAIL line and a final "DOCS-GATE PASS|FAIL" line.
# Exits 0 on full pass, 1 on any failure.
#
# Usage: test/docs_gate.sh
#===============================================================================
set -u

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || { echo "FAIL  cannot enter repo root $REPO_ROOT"; exit 1; }

failures=0

#------------------------------------------------------------------------------
# check_file <path> <label> : exists and non-empty
#------------------------------------------------------------------------------
check_file() {
    local f="$1" label="$2"
    if [[ ! -e "$f" ]]; then
        echo "FAIL  ${label}  (missing: $f)"
        failures=$((failures + 1))
    elif [[ ! -s "$f" ]]; then
        echo "FAIL  ${label}  (empty: $f)"
        failures=$((failures + 1))
    else
        echo "PASS  ${label}  ($f)"
    fi
}

#------------------------------------------------------------------------------
# check_placeholders <path> : stale placeholder wording detection
#------------------------------------------------------------------------------
check_placeholders() {
    local f="$1"
    [[ -e "$f" && -s "$f" ]] || return  # existence/empty handled elsewhere
    if grep -qiE 'placeholder for future|to be written|coming soon|under construction|TBD|lorem ipsum' "$f"; then
        echo "FAIL  stale placeholder wording in $f"
        failures=$((failures + 1))
    else
        echo "PASS  no stale placeholder wording in $f"
    fi
}

#------------------------------------------------------------------------------
# Assemble the full set of mandatory doc paths.
#------------------------------------------------------------------------------
mandatory=()

# Static top-level / policy / sdk docs (order preserved for a stable report).
while IFS= read -r p; do
    mandatory+=("$p")
done <<'EOF'
docs/refman/PROGRAMMERS_GUIDE.md
docs/refman/index.md
doc/MANIFEST.md
doc/DEVELOPER_TOOLING.md
doc/DOCS_POLICY.md
doc/GENERIC_ASPECT_CONFORMANCE.md
doc/FEATURE_STATUS.md
CHANGELOG.md
docs/sdk/GETTING_STARTED.md
docs/sdk/INSTALL.md
EOF

# Generated module pages: .md files under docs/refman carrying the refman.py
# generated marker in their header (first 5 lines), excluding index.md (already
# covered above). Matching against the header avoids false positives from
# hand-written files (e.g. PLAN.md) that merely quote the marker in prose.
if [[ -d docs/refman ]]; then
    mapfile -t mod_pages < <(
        for f in docs/refman/*.md; do
            if head -5 "$f" 2>/dev/null | grep -q 'generated by tools/refman.py'; then
                [[ "$f" != "docs/refman/index.md" ]] && printf '%s\n' "$f"
            fi
        done
    )
    if [[ ${#mod_pages[@]} -eq 0 ]]; then
        echo "FAIL  no generated module pages found under docs/refman/"
        failures=$((failures + 1))
    else
        for p in "${mod_pages[@]}"; do
            mandatory+=("$p")
        done
    fi
else
    echo "FAIL  docs/refman/ directory missing"
    failures=$((failures + 1))
fi

#------------------------------------------------------------------------------
# Run the checks.
#------------------------------------------------------------------------------
for p in "${mandatory[@]}"; do
    check_file "$p" "$(basename "$p")"
    check_placeholders "$p"
done

#------------------------------------------------------------------------------
# Verdict.
#------------------------------------------------------------------------------
if [[ ${#mandatory[@]} -eq 0 ]]; then
    echo "FAIL  no mandatory documents were enumerated; gate is vacuous"
    failures=$((failures + 1))
fi

if [[ $failures -eq 0 ]]; then
    echo "DOCS-GATE PASS"
    exit 0
fi

echo "DOCS-GATE FAIL (${failures} problem(s))"
exit 1
