// SPDX-License-Identifier: Apache-2.0

// Example of how async/await will integrate with the Vyb language
// This shows the conceptual integration, not working code yet

#include "vyb/runtime/async_runtime.hpp"
#include <iostream>
#include <thread>
#include <chrono>

using namespace vyb::runtime;

// Mock functions that simulate what the LLVM codegen will generate
namespace vyb_codegen_simulation {

// Simulates an async function that will be generated by LLVM codegen
std::shared_ptr<Future> async_function_example() {
    auto task_func = []() {
        std::cout << "Async function executing..." << std::endl;
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
        std::cout << "Async function completed!" << std::endl;
    };

    TaskId id = scheduleAsyncFunction(task_func);
    return awaitTask(id);
}

// Simulates another async function
std::shared_ptr<Future> fetch_data_async(const std::string& url) {
    auto task_func = [url]() {
        std::cout << "Fetching data from: " << url << std::endl;
        std::this_thread::sleep_for(std::chrono::milliseconds(150));
        std::cout << "Data fetched successfully!" << std::endl;
    };

    TaskId id = scheduleAsyncFunction(task_func);
    return awaitTask(id);
}

// Simulates an async function that awaits another async function
std::shared_ptr<Future> process_data_async() {
    auto task_func = []() {
        std::cout << "Starting data processing..." << std::endl;

        // This simulates: await fetch_data_async("https://api.example.com")
        auto future = fetch_data_async("https://api.example.com");
        future->wait(); // This is what 'await' will do

        std::cout << "Processing fetched data..." << std::endl;
        std::this_thread::sleep_for(std::chrono::milliseconds(75));
        std::cout << "Data processing completed!" << std::endl;
    };

    TaskId id = scheduleAsyncFunction(task_func);
    return awaitTask(id);
}

}

int main() {
    std::cout << "=== Vyb Async/Await Integration Demo ===" << std::endl;

    // Initialize runtime
    initializeAsyncRuntime();

    // Simulate what this Vyb code would generate:
    // ```
    // async fetch_data(url<String>)<String> -> {
    //     // async work here
    // }
    //
    // async process_data()<Void> -> {
    //     data<String> = await fetch_data("https://api.example.com");
    //     // process data
    // }
    //
    // main()<Void> -> {
    //     await process_data();
    // }
    // ```

    std::cout << "\n1. Running simple async function..." << std::endl;
    auto future1 = vyb_codegen_simulation::async_function_example();
    future1->wait();

    std::cout << "\n2. Running async function with await..." << std::endl;
    auto future2 = vyb_codegen_simulation::process_data_async();
    future2->wait();

    std::cout << "\n3. Running multiple async functions concurrently..." << std::endl;
    auto future3 = vyb_codegen_simulation::fetch_data_async("https://api1.example.com");
    auto future4 = vyb_codegen_simulation::fetch_data_async("https://api2.example.com");

    // Wait for both to complete (simulates await on multiple futures)
    future3->wait();
    future4->wait();

    // Statistics
    auto& runtime = getAsyncRuntime();
    std::cout << "\nRuntime Statistics:" << std::endl;
    std::cout << "Completed tasks: " << runtime.getCompletedTaskCount() << std::endl;
    std::cout << "Pending tasks: " << runtime.getPendingTaskCount() << std::endl;

    // Cleanup
    shutdownAsyncRuntime();

    std::cout << "\n✓ Async/await integration demo completed successfully!" << std::endl;
    std::cout << "\nThis demonstrates how Vyb's async/await will work:" << std::endl;
    std::cout << "- async functions return Future<T>" << std::endl;
    std::cout << "- await suspends until Future is ready" << std::endl;
    std::cout << "- Multiple async operations can run concurrently" << std::endl;
    std::cout << "- Runtime manages task scheduling automatically" << std::endl;

    return 0;
}