#include "vyb/bindgen.hpp"

#include <cctype>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

namespace vyb {
namespace bindgen {

namespace {

// --- tokenizer -------------------------------------------------------------

enum class Kind { Ident, Number, Str, Char, Punct, Eof };
struct Tok {
    Kind kind;
    std::string text;
};

// Strip block/line comments and whole preprocessor lines (`#...`) so the
// declarations we care about are recognizable without a real preprocessor.
std::string stripNoise(const std::string& src) {
    std::string out;
    out.reserve(src.size());
    size_t i = 0, n = src.size();
    bool atLineStart = true;
    while (i < n) {
        char c = src[i];
        if (atLineStart && c == '#') {
            while (i < n && src[i] != '\n') ++i;
            continue;
        }
        if (c == '/' && i + 1 < n && src[i + 1] == '/') {
            while (i < n && src[i] != '\n') ++i;
            continue;
        }
        if (c == '/' && i + 1 < n && src[i + 1] == '*') {
            i += 2;
            while (i + 1 < n && !(src[i] == '*' && src[i + 1] == '/')) ++i;
            i += 2;
            continue;
        }
        out.push_back(c);
        atLineStart = (c == '\n');
        ++i;
    }
    return out;
}

std::vector<Tok> tokenize(const std::string& s) {
    std::vector<Tok> toks;
    size_t i = 0, n = s.size();
    while (i < n) {
        char c = s[i];
        if (std::isspace(static_cast<unsigned char>(c))) { ++i; continue; }
        if (std::isalpha(static_cast<unsigned char>(c)) || c == '_') {
            size_t b = i;
            while (i < n && (std::isalnum(static_cast<unsigned char>(s[i])) || s[i] == '_')) ++i;
            toks.push_back({Kind::Ident, s.substr(b, i - b)});
            continue;
        }
        if (std::isdigit(static_cast<unsigned char>(c))) {
            size_t b = i;
            while (i < n && (std::isalnum(static_cast<unsigned char>(s[i])) || s[i] == '_')) ++i;
            toks.push_back({Kind::Number, s.substr(b, i - b)});
            continue;
        }
        if (c == '"') {
            size_t b = i; ++i;
            while (i < n && s[i] != '"') { if (s[i] == '\\') ++i; ++i; }
            ++i;
            toks.push_back({Kind::Str, s.substr(b, i - b)});
            continue;
        }
        if (c == '\'') {
            size_t b = i; ++i;
            while (i < n && s[i] != '\'') { if (s[i] == '\\') ++i; ++i; }
            ++i;
            toks.push_back({Kind::Char, s.substr(b, i - b)});
            continue;
        }
        toks.push_back({Kind::Punct, std::string(1, c)});
        ++i;
    }
    toks.push_back({Kind::Eof, ""});
    return toks;
}

// --- parser -----------------------------------------------------------------

class CParser {
public:
    explicit CParser(const std::string& src) : toks_(tokenize(stripNoise(src))) {}

    std::string run(std::vector<std::string>& warningsOut) {
        while (cur().kind != Kind::Eof) {
            skipDeclarationQualifiers();
            if (isKw("typedef")) { parseTypedef(); continue; }
            if (isKw("struct")) { parseStructDecl(false); continue; }
            if (isKw("enum")) { parseEnumDecl(false); continue; }
            if (!tryParseFunction()) {
                skipToSeparator();
            }
        }
        std::ostringstream os;
        os << "# Auto-generated by `vyb bindgen`. Do not edit.\n\n";
        emitTypes(os);
        emitFunctions(os);
        warningsOut = warnings_;
        return os.str();
    }

private:
    std::vector<Tok> toks_;
    size_t p_ = 0;
    std::vector<std::string> warnings_;

    std::map<std::string, std::string> aliases_;                  // typedef -> Vyb type text / canonical name
    std::map<std::string, std::vector<std::pair<std::string, std::string>>> structs_;
    std::map<std::string, std::vector<std::string>> enums_;
    std::vector<std::string> declOrder_;                           // emitted type names, declaration order
    std::set<std::string> emittedTypes_;

    struct Param { std::string name; std::string type; };
    struct Func {
        std::string name;
        std::vector<Param> params;
        std::string ret;
        bool varargs = false;
    };
    std::vector<Func> funcs_;

    Tok& cur() { return toks_[p_]; }
    Tok& peek(int d = 1) {
        size_t q = p_ + d;
        return q < toks_.size() ? toks_[q] : toks_.back();
    }
    void advance() { if (cur().kind != Kind::Eof) ++p_; }

    bool isIdent(const Tok& t) const { return t.kind == Kind::Ident; }
    bool isKw(const char* s) { return isIdent(cur()) && cur().text == s; }
    bool atPunct(const char* s) { return cur().kind == Kind::Punct && cur().text == s; }
    bool atPunct(int d, const char* s) { return peek(d).kind == Kind::Punct && peek(d).text == s; }

    void skipDeclarationQualifiers() {
        static const std::set<std::string> quals = {
            "extern", "static", "inline", "register", "const", "volatile",
            "restrict", "_Nonnull", "_Nullable", "auto", "__attribute__"
        };
        while (isIdent(cur()) && quals.count(cur().text)) {
            if (cur().text == "__attribute__") {
                while (!atPunct("(") && cur().kind != Kind::Eof) advance();
                if (atPunct("(")) skipBalanced("(", ")");
            } else {
                advance();
            }
        }
    }

    void skipBalanced(const char* open, const char* close) {
        int depth = 0;
        while (cur().kind != Kind::Eof) {
            if (atPunct(open)) ++depth;
            else if (atPunct(close)) { --depth; if (depth == 0) { advance(); return; } }
            advance();
        }
    }

    void skipToSeparator() {
        int depth = 0;
        while (cur().kind != Kind::Eof) {
            if (atPunct("{")) ++depth;
            else if (atPunct("}")) { if (depth == 0) { advance(); return; } --depth; }
            else if (atPunct(";") && depth == 0) { advance(); return; }
            else if (depth == 0 && (isKw("typedef") || isKw("struct") || isKw("enum"))) { return; }
            advance();
        }
    }

    void skipSemicolon() {
        while (isIdent(cur()) || atPunct("*") || atPunct(",")) advance();
        if (atPunct(";")) advance();
    }

    bool atEllipsis() {
        return atPunct(".") && atPunct(1, ".") && atPunct(2, ".");
    }

    // --- type parsing ---

    // Wraps a base C type in the pointer form an explicit `*` uses (mirrors the
    // tail of parseCType): `char*` -> CString, `T*` -> loc<T>, deeper -> nested loc.
    std::string pointerWrap(const std::string& base, int ptrDepth) {
        if (ptrDepth <= 0) return base;
        if (base == "CChar" && ptrDepth == 1) return "CString";
        std::string inner = base;
        for (int i = 1; i < ptrDepth; ++i) inner = "loc<" + inner + ">";
        return "loc<" + inner + ">";
    }

    // Parses one C type (base + optional pointer stars). Returns the mapped Vyb
    // type text, or "" on failure. Optional out-params: records whether a pointer
    // was seen, and (for function-pointer types) the declaration name so the
    // caller can use it as a param name / typedef alias.
    std::string parseCType(bool* isPointer = nullptr, std::string* nameOut = nullptr) {
        if (isPointer) *isPointer = false;
        if (nameOut) nameOut->clear();
        while (isIdent(cur()) &&
               (cur().text == "const" || cur().text == "volatile" || cur().text == "restrict")) {
            advance();
        }

        bool isUnsigned = false;
        if (isKw("unsigned")) { isUnsigned = true; advance(); }
        else if (isKw("signed")) { advance(); }

        std::string base;
        if (isKw("void")) { base = "CVoid"; advance(); }
        else if (isKw("char")) { base = isUnsigned ? "CUChar" : "CChar"; advance(); }
        else if (isKw("short")) { base = isUnsigned ? "CUShort" : "CShort"; advance(); if (isKw("int")) advance(); }
        else if (isKw("long")) {
            advance();
            if (isKw("long")) { advance(); base = isUnsigned ? "UInt64" : "Int"; }
            else { base = isUnsigned ? "CULong" : "CLong"; }
            if (isKw("int")) advance();
        }
        else if (isKw("int")) { base = isUnsigned ? "CUInt" : "CInt"; advance(); }
        else if (isKw("float")) { base = "CFloat"; advance(); }
        else if (isKw("double")) { base = "CDouble"; advance(); }
        else if (isKw("size_t")) { base = "CSize"; advance(); }
        else {
            if (isKw("struct") || isKw("enum")) advance();
            if (isIdent(cur())) { base = cur().text; advance(); }
            else return "";
        }

        int ptrDepth = 0;
        while (atPunct("*")) {
            ++ptrDepth;
            advance();
            while (isIdent(cur()) &&
                   (cur().text == "const" || cur().text == "volatile" || cur().text == "restrict")) {
                advance();
            }
        }

        if (!base.empty() && aliases_.count(base)) base = aliases_[base];

        // C function-pointer type: `RET ( *  <name> ) ( PARAMS )`.
        if (!base.empty() && atPunct("(") && atPunct(1, "*")) {
            if (isPointer) *isPointer = true;
            advance(); // (
            advance(); // *
            if (isIdent(cur())) {            // the pointer's declared name
                if (nameOut) *nameOut = cur().text;
                advance();
            }
            while (!atPunct(")") && cur().kind != Kind::Eof) advance();
            if (atPunct(")")) advance();

            // The function-pointer's own parameter list.
            std::string fn = "fn(";
            bool anyParam = false;
            if (atPunct("(")) {
                advance();
                if (!(isKw("void") && atPunct(1, ")"))) {  // `(void)` == no params
                    while (!atPunct(")") && cur().kind != Kind::Eof) {
                        std::string pt = parseCType();
                        if (pt.empty()) break;
                        if (anyParam) fn += ", ";
                        fn += pt;
                        anyParam = true;
                        if (isIdent(cur())) advance(); // inner param name
                        if (atPunct(",")) advance();
                    }
                }
                if (atPunct(")")) advance();
            }
            fn += ") -> " + pointerWrap(base, ptrDepth);
            // A C function pointer is a bare code pointer (single `ptr`), not a
            // Vyb closure (`fn(...)` lowers to `{ env, fn }`). Wrap it in `loc<>`
            // so the binding carries the C ABI and accepts a Vyb function.
            return "loc<" + fn + ">";
        }

        return pointerWrap(base, ptrDepth);
    }

    // --- declarations ---

    void parseTypedef() {
        advance(); // typedef
        skipDeclarationQualifiers();
        if (isKw("struct")) { parseStructDecl(true); return; }
        if (isKw("enum")) { parseEnumDecl(true); return; }

        size_t mark = p_;
        std::string fpname;
        std::string type = parseCType(nullptr, &fpname);
        if (type.empty()) { p_ = mark; skipToSeparator(); return; }
        while (atPunct("*")) { type = "loc<" + type + ">"; advance(); }
        std::string alias;
        if (!fpname.empty()) {                // function-pointer typedef: name is inside the type
            alias = fpname;
        } else if (isIdent(cur())) {
            alias = cur().text;
            advance();
        } else {
            p_ = mark;
            skipToSeparator();
            return;
        }
        aliases_[alias] = type;
        skipSemicolon();
    }

    void parseStructDecl(bool isTypedef) {
        advance(); // struct
        std::string tag;
        if (isIdent(cur())) { tag = cur().text; advance(); }

        // typedef without body: `typedef struct Point PP;`
        if (isTypedef && !atPunct("{")) {
            while (atPunct("*")) advance();
            if (isIdent(cur()) && !tag.empty()) {
                std::string alias = cur().text;
                advance();
                aliases_[alias] = tag;
            }
            skipSemicolon();
            return;
        }
        // plain forward declaration: `struct Point;`
        if (!isTypedef && !atPunct("{")) { skipSemicolon(); return; }

        // parse body; the typedef alias (if any) is captured after '}'
        std::string alias;
        std::string name = tag;

        std::vector<std::pair<std::string, std::string>> fields;
        if (atPunct("{")) {
            advance();
            while (cur().kind != Kind::Eof && !atPunct("}")) {
                size_t mark = p_;
                bool fp = false;
                std::string type = parseCType(&fp);
                if (type.empty()) { p_ = mark; skipToStructClose(); return; }
                if (!isIdent(cur())) { p_ = mark; skipToStructClose(); return; }
                std::string fname = cur().text;
                advance();
                if (atPunct(":")) { // bitfield: consume width then separator
                    while (!atPunct(";") && !atPunct(",") && !atPunct("}") && cur().kind != Kind::Eof) advance();
                }
                if (atPunct("[")) { // array field: skip [N]
                    while (!atPunct("]") && cur().kind != Kind::Eof) advance();
                    if (atPunct("]")) advance();
                }
                fields.push_back({fname, type});
                if (atPunct(";")) advance();        // C field separator
                else if (atPunct(",")) advance();   // rare but allowed
                else if (atPunct("}")) break;
                else advance();                     // keep progress on unexpected tokens
            }
            if (!atPunct("}")) { skipToSeparator(); return; }
            advance(); // }
        }

        if (isTypedef && isIdent(cur())) {
            alias = cur().text;
            advance();
        }
        std::string finalName = !alias.empty() ? alias : name;
        if (finalName.empty()) {
            warnings_.push_back("skipping anonymous struct (no typedef name)");
            skipSemicolon();
            return;
        }
        if (!fields.empty()) {
            if (emittedTypes_.insert(finalName).second) declOrder_.push_back(finalName);
            structs_[finalName] = fields;
        }
        if (isTypedef) aliases_[finalName] = finalName;
        if (!alias.empty() && alias != finalName) aliases_[alias] = finalName;
        else if (!tag.empty() && alias.empty()) aliases_[tag] = finalName;
        skipSemicolon();
    }

    void skipToStructClose() {
        while (cur().kind != Kind::Eof && !atPunct("}")) advance();
        if (atPunct("}")) advance();
    }

    void parseEnumDecl(bool isTypedef) {
        advance(); // enum
        std::string tag;
        if (isIdent(cur())) { tag = cur().text; advance(); }

        if (isTypedef && !atPunct("{")) {
            while (atPunct("*")) advance();
            if (isIdent(cur()) && !tag.empty()) {
                std::string alias = cur().text;
                advance();
                aliases_[alias] = tag;
            }
            skipSemicolon();
            return;
        }
        if (!isTypedef && !atPunct("{")) { skipSemicolon(); return; }

        std::vector<std::string> variants;
        bool sawInit = false;
        advance(); // {
        while (cur().kind != Kind::Eof && !atPunct("}")) {
            if (isIdent(cur())) {
                std::string v = cur().text;
                advance();
                if (atPunct("=")) {
                    sawInit = true;
                    while (!atPunct(",") && !atPunct("}") && cur().kind != Kind::Eof) advance();
                }
                variants.push_back(v);
            } else {
                advance();
            }
            if (atPunct(",")) advance();
        }
        if (!atPunct("}")) { skipToSeparator(); return; }
        advance(); // }

        std::string alias;
        if (isTypedef && isIdent(cur())) { alias = cur().text; advance(); }
        std::string finalName = !alias.empty() ? alias : tag;
        if (finalName.empty()) {
            warnings_.push_back("skipping anonymous enum (no typedef name)");
            skipSemicolon();
            return;
        }
        if (sawInit) warnings_.push_back("enum '" + finalName + "' has explicit values; Vyb enums are sequential from 0");
        if (emittedTypes_.insert(finalName).second) declOrder_.push_back(finalName);
        enums_[finalName] = variants;
        if (isTypedef) aliases_[finalName] = finalName;
        if (!alias.empty() && alias != finalName) aliases_[alias] = finalName;
        else if (!tag.empty() && alias.empty()) aliases_[tag] = finalName;
        skipSemicolon();
    }

    bool tryParseFunction() {
        size_t mark = p_;
        bool isPtr = false;
        std::string ret = parseCType(&isPtr);
        if (ret.empty()) { p_ = mark; return false; }
        if (!isIdent(cur())) { p_ = mark; return false; }
        std::string name = cur().text;
        advance();
        if (!atPunct("(")) { p_ = mark; return false; }
        advance(); // (

        Func f;
        f.name = name;
        f.ret = ret;

        size_t arg = 0;
        bool keep = true;
        while (cur().kind != Kind::Eof && !atPunct(")")) {
            if (atEllipsis()) {
                f.varargs = true;
                advance(); advance(); advance();
                break;
            }
            if (atPunct(",")) { advance(); continue; }
            if (isKw("void") && atPunct(1, ")")) { advance(); break; } // (void)

            size_t pmark = p_;
            bool pptr = false;
            std::string fpname;
            std::string ptype = parseCType(&pptr, &fpname);
            if (ptype.empty()) { keep = false; p_ = pmark; break; }
            std::string pname;
            if (!fpname.empty()) pname = fpname;
            else if (isIdent(cur())) { pname = cur().text; advance(); }
            // C array parameters decay to pointers (`T a[N]` / `T a[]` == `T*`),
            // so `char out[64]` is a `char*` buffer, not a scalar byte. Map the
            // decayed type to the same pointer form an explicit `*` would use.
            if (atPunct("[")) {
                while (atPunct("[")) {
                    while (!atPunct("]") && cur().kind != Kind::Eof) advance();
                    if (atPunct("]")) advance();
                }
                if (!pptr && !ptype.empty()) {
                    if (ptype == "CChar") ptype = "CString";       // char buf[N] -> char*
                    else ptype = "loc<" + ptype + ">";             // T buf[N]   -> T*
                }
            }
            if (pname.empty()) pname = "a" + std::to_string(arg);
            f.params.push_back({pname, ptype});
            ++arg;
            while (atPunct(",")) advance();
            if (atPunct(")")) break;
        }

        if (keep && atPunct(")")) {
            advance();
            while (atPunct(",")) advance();
            if (atPunct(";")) advance();
            else { while (!atPunct(";") && cur().kind != Kind::Eof) advance(); if (atPunct(";")) advance(); }
            funcs_.push_back(std::move(f));
            return true;
        }
        p_ = mark;
        return false;
    }

    // --- emitter ---

    void emitTypes(std::ostringstream& os) {
        for (const std::string& name : declOrder_) {
            if (structs_.count(name)) {
                os << "share(all)\n#[repr(C)]\nstruct " << name << " {\n";
                for (auto& f : structs_[name]) {
                    os << "    " << f.first << "<" << f.second << ">,\n";
                }
                os << "}\n\n";
            } else if (enums_.count(name)) {
                os << "share(all)\nenum " << name << " { ";
                for (size_t k = 0; k < enums_[name].size(); ++k) {
                    if (k) os << ", ";
                    os << enums_[name][k];
                }
                os << " }\n\n";
            }
        }
    }

    void emitFunctions(std::ostringstream& os) {
        if (funcs_.empty()) return;
        // Emitted as bodyless `share(all)` declarations (no `extern "C"` block)
        // so the bindings import like ordinary Vyb functions while still
        // lowering to ExternalLinkage forward declarations that resolve to the
        // C symbols at link/JIT time. (Extern "C" block members are not shared
        // across module imports.)
        for (const auto& f : funcs_) {
            os << "share(all)\n";
            os << f.name << "(";
            for (size_t i = 0; i < f.params.size(); ++i) {
                if (i) os << ", ";
                os << f.params[i].name << "<" << f.params[i].type << ">";
            }
            if (f.varargs) {
                if (!f.params.empty()) os << ", ";
                os << "...";
            }
            os << ")<" << f.ret << ">" << "\n\n";
        }
    }
};

} // namespace

std::string generateBindings(const std::string& headerSource,
                             std::vector<std::string>* warnings) {
    std::vector<std::string> collected;
    CParser parser(headerSource);
    std::string out = parser.run(collected);
    if (warnings) *warnings = std::move(collected);
    return out;
}

} // namespace bindgen
} // namespace vyb
